version: '3.10'

services:
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
        - static_data:/app/static
        ports:
        - "8000:8000"
        restart: always
        env_file:
        - ./.env.dev
        depends_on:
        - db

    db:
        image: postgres:13.0-alpine
        restart: always
        env_file:
        - .env.dev
        volumes:
        - postgres_data:/var/lib/postgresql/data

volumes:
  static_data:
  postgres_data:
